export const LOGIN_USER = 'login_user'
export const REGISTER_USER = 'register_user'
export const AUTH_USER = 'auth_user'
export const LOGOUT_USER = 'logout_user'
export const ADD_TO_CARD_USER = 'add_to_card_user'
export const GET_CARD_ITEMS_USER = 'get_card_items_user'
export const REMOVE_CARD_ITEMS_USER = 'remove_card_items_user'
export const ON_SUCCESS_BUY_USER = 'on_success_buy_user'
